import { useEffect, useRef, useState } from 'react'
import { useStore } from '../../state/store.jsx'
import { getSettings } from '../../lib/callModel.js'
import { sttSupported, ttsSupported, onVoicesReady } from '../../lib/voice.js'
import { X, Download, Upload } from './Icons.jsx'

export default function Settings() {
  const { state, actions } = useStore()
  const [s, setS] = useState(getSettings())
  if (!state.settingsOpen) return null

  const save = () => { actions.updateSettings(s); actions.closeSettings(); actions.toast('Settings saved') }
  const field = 'w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-sea/45'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[rgba(10,31,28,0.45)] backdrop-blur-sm animate-fade-in" onClick={actions.closeSettings}>
      <div className="w-full max-w-md max-h-[88vh] rounded-2xl bg-surface shadow-xl ring-1 ring-line flex flex-col overflow-hidden" onClick={(e) => e.stopPropagation()}>
        <div className="shrink-0 flex items-center justify-between p-5 pb-3 border-b border-line">
          <h2 className="text-lg font-semibold">Model settings</h2>
          <button onClick={actions.closeSettings} className="text-ink2 hover:text-accentink"><X /></button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 pt-4">
        <div className="space-y-4 text-sm">
          <div>
            <label className="block mb-1 font-medium">Answer engine</label>
            <div className="grid grid-cols-3 gap-2">
              {[
                { id: 'free', label: 'Free AI', sub: 'no key' },
                { id: 'gemini', label: 'Gemini', sub: 'your key' },
                { id: 'custom', label: 'Custom', sub: 'any key' },
              ].map((p) => (
                <button key={p.id} onClick={() => setS((prev) => {
                  const next = { ...prev, provider: p.id }
                  if (p.id === 'gemini') {
                    if (!/gemini/i.test(prev.model || '')) next.model = 'gemini-2.5-flash'
                    if (!/generativelanguage/i.test(prev.baseUrl || '')) next.baseUrl = 'https://generativelanguage.googleapis.com/v1beta'
                  }
                  if (p.id === 'custom') {
                    if (/gemini/i.test(prev.model || '') || !prev.model) next.model = 'gpt-4o-mini'
                    if (/generativelanguage/i.test(prev.baseUrl || '') || !prev.baseUrl) next.baseUrl = 'https://api.openai.com/v1'
                  }
                  return next
                })}
                  className={`rounded-lg px-2 py-2 ring-1 transition text-center ${s.provider === p.id ? 'bg-deep text-white ring-deep' : 'ring-line hover:bg-tint'}`}>
                  <div className="text-sm font-medium">{p.label}</div>
                  <div className={`text-[10px] ${s.provider === p.id ? 'text-white/80' : 'text-ink2'}`}>{p.sub}</div>
                </button>
              ))}
            </div>
          </div>

          {s.provider === 'free' && (
            <p className="text-xs text-ink2 bg-tint rounded-lg p-3 leading-relaxed">
              <b>Free AI</b> answers open-ended questions about anything — no API key, no cost, no extra setup (it runs through the app’s built-in proxy). Exact math/time are computed locally and facts stay grounded in cited Wikipedia; everything else is generated by a free model (pollinations.ai), so your messages are sent there. The free service can occasionally be slow or busy. For your own higher-quality key-based model, choose <b>Gemini</b> and add a key.
            </p>
          )}

          {s.provider === 'gemini' && (
            <>
              <div>
                <label className="block mb-1 font-medium">Gemini API key</label>
                <input type="password" className={field} placeholder="AIza…" value={s.apiKey}
                  onChange={(e) => setS({ ...s, apiKey: e.target.value })} />
                <p className="mt-1 text-xs text-ink2">Get a free key at <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer" className="text-accentink underline">aistudio.google.com/apikey</a>. Stored only in this browser; calls go direct to Google. Your selection is kept — if Gemini fails, that reply comes from Free AI.</p>
              </div>
              <div>
                <label className="block mb-1 font-medium">Model</label>
                <input className={field} value={s.model} onChange={(e) => setS({ ...s, model: e.target.value })} placeholder="gemini-2.5-flash" />
                <p className="mt-1 text-xs text-ink2">e.g. <code>gemini-2.5-flash</code> (fast, free tier) or <code>gemini-2.5-pro</code>.</p>
              </div>
            </>
          )}

          {s.provider === 'custom' && (
            <>
              <div>
                <label className="block mb-1 font-medium">API key</label>
                <input type="password" className={field} placeholder="sk-…" value={s.apiKey}
                  onChange={(e) => setS({ ...s, apiKey: e.target.value })} />
                <p className="mt-1 text-xs text-ink2">Any <b>OpenAI-compatible</b> provider — OpenAI, OpenRouter, Groq, Together, a local server, etc. Stored only in this browser; calls go server-side through the app’s proxy (no CORS issues).</p>
              </div>
              <div>
                <label className="block mb-1 font-medium">Base URL</label>
                <input className={field} value={s.baseUrl} onChange={(e) => setS({ ...s, baseUrl: e.target.value })} placeholder="https://api.openai.com/v1" />
                <p className="mt-1 text-xs text-ink2">The API base (it calls <code>{'{base}/chat/completions'}</code>). E.g. <code>https://openrouter.ai/api/v1</code>, <code>https://api.groq.com/openai/v1</code>.</p>
              </div>
              <div>
                <label className="block mb-1 font-medium">Model</label>
                <input className={field} value={s.model} onChange={(e) => setS({ ...s, model: e.target.value })} placeholder="gpt-4o-mini" />
              </div>
            </>
          )}

        </div>

        <VoicePanel />
        <DataPanel />
        </div>

        <div className="shrink-0 border-t border-line p-4 flex justify-end gap-2 bg-surface">
          <button onClick={actions.closeSettings} className="rounded-lg px-4 py-2 text-sm ring-1 ring-line">Cancel</button>
          <button onClick={save} className="rounded-lg px-4 py-2 text-sm bg-deep text-white font-medium">Save</button>
        </div>
      </div>
    </div>
  )
}

function DataPanel() {
  const { actions } = useStore()
  const fileRef = useRef(null)
  return (
    <div className="mt-5 pt-4 border-t border-line">
      <h3 className="text-sm font-semibold flex items-center gap-2 mb-2">☁️ Your data</h3>
      <p className="text-xs text-ink2 mb-2 leading-relaxed">Chats sync in real time across open tabs/windows. Export a backup or import it on another device.</p>
      <div className="flex gap-2">
        <button onClick={actions.exportData} className="flex-1 flex items-center justify-center gap-1.5 text-sm py-2 rounded-lg ring-1 ring-line hover:bg-tint">
          <Download size={15} /> Export
        </button>
        <button onClick={() => fileRef.current?.click()} className="flex-1 flex items-center justify-center gap-1.5 text-sm py-2 rounded-lg ring-1 ring-line hover:bg-tint">
          <Upload size={15} /> Import
        </button>
        <input ref={fileRef} type="file" accept="application/json" hidden
          onChange={(e) => { const f = e.target.files?.[0]; e.target.value = ''; if (f) actions.importData(f) }} />
      </div>
    </div>
  )
}

function VoicePanel() {
  const { state, actions } = useStore()
  const v = state.voice
  const [voices, setVoices] = useState([])
  useEffect(() => onVoicesReady(setVoices), [])
  const enVoices = voices.filter((x) => /en[-_]/i.test(x.lang))

  return (
    <div className="mt-5 pt-4 border-t border-line">
      <h3 className="text-sm font-semibold flex items-center gap-2 mb-2">🎙️ Voice assistant</h3>

      {!sttSupported && !ttsSupported && (
        <p className="text-xs text-ink2">This browser doesn’t support the Web Speech API. Try Chrome, Edge, or Safari.</p>
      )}

      <div className="space-y-2.5 text-sm">
        {ttsSupported && (
          <label className="flex items-center justify-between cursor-pointer">
            <span>Read replies aloud</span>
            <input type="checkbox" checked={v.autoSpeak} onChange={(e) => actions.setVoice({ autoSpeak: e.target.checked })} />
          </label>
        )}
        {sttSupported && (
          <label className="flex items-center justify-between cursor-pointer">
            <span>Auto-send after speaking <span className="text-ink2">(hands-free)</span></span>
            <input type="checkbox" checked={v.autoSend} onChange={(e) => actions.setVoice({ autoSend: e.target.checked })} />
          </label>
        )}
        {ttsSupported && enVoices.length > 0 && (
          <div>
            <label className="block mb-1 text-ink2 text-xs">Voice</label>
            <select value={v.voiceURI} onChange={(e) => actions.setVoice({ voiceURI: e.target.value })}
              className="w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-sea/45">
              <option value="">Default ({enVoices[0]?.name})</option>
              {enVoices.map((x) => <option key={x.voiceURI} value={x.voiceURI}>{x.name} — {x.lang}</option>)}
            </select>
          </div>
        )}
        {ttsSupported && (
          <div>
            <label className="block mb-1 text-ink2 text-xs">Speaking rate · {v.rate.toFixed(2)}×</label>
            <input type="range" min="0.6" max="1.4" step="0.05" value={v.rate}
              onChange={(e) => actions.setVoice({ rate: parseFloat(e.target.value) })}
              className="w-full accent-[#218074]" />
          </div>
        )}
      </div>

      <p className="mt-2 text-xs text-ink2 leading-relaxed">
        Tap the 🎙️ mic in the composer to talk; the 🔊 toggle next to it reads replies aloud. Each answer also has a read-aloud button. All on-device via the browser — no API key.
      </p>
    </div>
  )
}
